name: siggwon-moa Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create env
        run: |
          echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .env
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
          echo MYSQL_DB=${{ secrets.MYSQL_DB }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DATABASE_URL=mysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.MYSQL_DB }} >> .env
          echo PORT=80 >> .env
          echo JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }} >> .env
          echo JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} >> .env
          echo BCRYPT_SALT_ROUNDS=${{ secrets.BCRYPT_SALT_ROUNDS }} >> .env
          echo VUE_SERVER=${{ secrets.VUE_SERVER }} >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t devkyu96/siggwon-moa:v1 .

      - name: Push Docker image
        run: docker push devkyu96/siggwon-moa:v1

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |

            echo "Pulling the latest Docker image..."
            docker pull devkyu96/siggwon-moa:v1

            echo "Stopping and removing existing container if running..."
            docker stop siggwon-prd || true
            docker rm siggwon-prd || true

            echo "Running the new container..."
            docker run -d --name siggwon-prd -p 80:80

            echo "Server Start"
